# Generated by Django 5.1.2 on 2024-10-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
